export const getInlineStylesSelect = (errors, touched) => ({
  control: (base) => ({
    ...base,
    borderColor: errors.departement && touched.departement ? "red" : "#EEEEF6",
    width: "100%",
    padding: "12px 0 12px 20px",
    backgroundColor: "#EEEEF6",
    borderRadius: "8px",
    cursor: "pointer",
    color: "#172755",
    fontFamily: "Roboto Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22.4px",
    "&:hover": {
      borderColor: "transparent",
    },
  }),
  input: (base) => ({
    ...base,
    padding: "0px",
    margin: "0px",
    fontFamily: "Roboto Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22.4px",
    color: "#172755",
  }),
  valueContainer: (base) => ({
    ...base,
    padding: "0px",
    marginLeft: "0px",
    marginRight: "auto",
  }),
  placeholder: (base) => ({
    ...base,
    color: "#8794BA",
    margin: "0px",
    fontFamily: "Roboto Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22.4px",
  }),
  menu: (base) => ({
    ...base,
    backgroundColor: "#ffff",
    border: "2px solid rgba(238, 238, 246, 0.1)",
    borderRadius: "8px",
  }),
  option: (base, { isFocused, isSelected }) => ({
    ...base,
    fontFamily: "Roboto Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "22.4px",
    color: "#172755",
    cursor: "pointer",
  }),
});
